[package]
name = "zoda-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
binius_core = { path = "../binius/crates/core" }
binius_field = { path = "../binius/crates/field" }
binius_hash = { path = "../binius/crates/hash" }
rand = "0.8.5"
rs_merkle = "1.4.2"
sha2 = "0.10.8"
